cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
    --partition={resources.partition}
    --gres={resources.gres}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
default-resources:
  - partition="cpu"
  - gres=null
  - mem_mb=4000
  - threads=1
residue: aceh
density: 1000.0
side_length: 35
qm:
  basis: cc-pVTZ
  xc: PBE0
  optimize: true
  harmonic: true
  hessian: true
  thermo: true
  gradient: true
md:
  temperatures: [100, 200, 300]
  pressures: [1.0, 2.0, 3.0]
  integrator: Langevin
  schedule: [minimization, equilibration, NPT]
cluster:
  n_find: 2
  stride: 1
