version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements: []
      # Avoid pulling heavy CUDA/optional deps that aren't needed for docs
      # RTD v2 does not support passing --no-deps directly, so rely on
      # autodoc_mock_imports in docs/conf.py to prevent importing heavy libs.

sphinx:
  configuration: docs/conf.py
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/requirements.yaml

sphinx:
  configuration: docs/conf.py
