# Main conda environment for MMML (CPU version)
# For GPU support, use environment-gpu.yml instead
name: mmml
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  
  # Core scientific computing
  - numpy
  - scipy
  - pandas
  - matplotlib>=3.5
  
  # JAX ecosystem (CPU version)
  - jax
  - jaxlib
  
  # ML utilities
  - pip
  - git
  
  # Chemistry and visualization
  - ase
  - pyyaml
  
  # Utilities
  - tqdm
  - rich-cli
  
  # Build tools
  - gfortran
  - cmake
  - make
  
  # PIP-only dependencies that are not available in conda or better installed via pip
  - pip:
      # JAX ecosystem extensions
      - dm-haiku
      - flax
      - optax
      - chex
      - jaxtyping
      - jmp
      - jraph
      - orbax-checkpoint
      - jax-md @ git+https://github.com/google/jax-md.git@05221c551e71f1b5f64458c0e3533452c22efec0
      
      # ML utilities
      - ml-dtypes
      - ml-collections
      - einops
      
      # Hydra configuration
      - hydra-core>=1.3.0
      - omegaconf>=2.3.0
      
      # Utilities
      - tabulate
      - typing-extensions
      
      # Install mmml in editable mode (run this from the repo root)
      - -e .

