# Conda environment for MMML with GPU support (CUDA 12)
name: mmml-gpu
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python>=3.11,<3.13
  
  # CUDA toolkit
  - cuda-toolkit=12
  - cudnn>=8
  
  # Core scientific computing
  - numpy
  - scipy
  - pandas
  - matplotlib>=3.5
  
  # JAX ecosystem (GPU will be installed via pip for better CUDA compatibility)
  
  # Chemistry and visualization
  - ase
  - pyyaml
  
  # Utilities
  - tqdm
  - rich-cli
  - pip
  - git
  
  # Build tools for compiling extensions
  - gfortran
  - cmake
  - make
  - openblas
  - liblapack
  
  # PIP-only dependencies
  - pip:
      # JAX with CUDA support (must be installed from specific index)
      - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - jax[cuda12]>=0.4.20
      - jaxlib[cuda12]>=0.4.20
      - cupy-cuda12x>=13.0.0
      - cutensor-cu12>=2.0.0
      - e3x
      - plotnine
      - patchworklib
      # JAX ecosystem
      - dm-haiku
      - flax
      - optax
      - chex
      - jaxtyping
      - jmp
      - jraph
      - orbax-checkpoint
      - jax-md @ git+https://github.com/google/jax-md.git@05221c551e71f1b5f64458c0e3533452c22efec0
      
      # ML utilities
      - ml-dtypes
      - ml-collections
      - einops
      
      # Hydra configuration
      - hydra-core>=1.3.0
      - omegaconf>=2.3.0
      
      # Utilities
      - tabulate
      - typing-extensions
      
      # Install mmml in editable mode (run this from the repo root)
      - -e .

