cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
    --partition={resources.partition}
    --gres={resources.gres}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
default-resources:
  - slurm_account="boittier"
  - partition="cpu"
  - gres=null
  - mem_mb=4000
  - threads=1
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 2
latency-wait: 260
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True