cluster: "sbatch --parsable --job-name=smk-{rule}-{wildcards} --output=logs/{rule}/{rule}-{wildcards}-%j.out --error=logs/{rule}/{rule}-{wildcards}-%j.err --partition={resources.partition} --gres={resources.gres}"
cluster-status: "status-sacct.sh"
jobs: 100
default-resources:
  - partition="cpu"
  - gres=null
  - mem_mb=4000
  - threads=1
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True 