# Example Snakemake config for dcmnet training

experiments:
  exp_default:
    data_files:
      - data/qm9-esp-dip-40000-0.npz
      - data/qm9-esp-dip-40000-1.npz
      - data/qm9-esp-dip-40000-2.npz
    extra_args: "--type default --num_epochs 10 --batch_size 8 --esp_w 10000.0"

  exp_dipole:
    data_files:
      - data/qm9-esp-dip-40000-0.npz
      - data/qm9-esp-dip-40000-1.npz
      - data/qm9-esp-dip-40000-2.npz
    extra_args: "--type dipole --num_epochs 10 --batch_size 8 --esp_w 10000.0" 