jobs: 10
default-resources:
  - partition="cpu"
  - gres=null
  - mem_mb=40000
  - threads=10
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 2
latency-wait: 260
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
