residue: dete 
density: 713.0
side_length: 35.0



md:
  temperatures: [300, 300, 300]
  pressures: [1.0, 1.0, 1.0]
  integrator: Langevin
  schedule: [minimization, equilibration, NPT]
  steps: 1000000
  timestep: 1.0

cluster:
  n_find: 2
  stride: 1

