list(APPEND charmm_cxx_files
source/blade_api/dynamics.cxx
source/domdec/enb_core_vec.cpp
source/domdec/enb_core_wrapper.cpp
source/machdep/gpucount.cpp
source/machdep/uninf.cpp
source/nbonds/helpme.cpp
source/opencl/ocl_util.cpp
source/openmm/customForces.cpp
source/openmm/forcesStore.cpp
source/openmm/ommPlus.cpp
source/openmm/torch.cpp
source/util/pack.cpp
source/mlmm/type_libt_dummy.cxx
source/mlmm/type_libt_dpmm.cxx
source/mlmm/type_libt_tani.cxx
source/mlmm/type_pyth_custom.cxx
source/mlmm/type_pyth.cxx
source/mndint/mndo97_dpmm.cxx
)
