"""Live CHARMM checks for ML torsions under the zeroed-CGenFF MLpot registration.

``zero_mlpot_psf_mm_terms`` zeroes bonded terms with ``READ PARAM APPEND FLEX``
of ``zeroed_bonded_par_all36_cgenff.prm``. In FLEX append mode each appended
dihedral row overwrites only the last stored entry with the same four atom
types, so multi-term dihedrals keep their other terms (issue #217). For one
ethanol, the n=1 and n=2 terms of ``CG331-CG321-OG311-HGP1`` survive
(0.28943 kcal/mol of the 3.23353 kcal/mol CGenFF DIHE).

Registration therefore also deletes the PSF dihedral/improper/CMAP terms of ML
atoms. These tests pin down:

* the CHARMM APPEND behaviour itself (documented, not a bug in mmml);
* the fixed registration path: ML bonded terms are exactly zero, also with
  the all-ML ``SKIPE`` of bonded terms lifted;
* deleting ML torsions leaves VDW/ELEC unchanged (exclusions and 1-4 pairs are
  built from the bond list, which is kept);
* the hybrid case (#225): ML atoms move to zero-bonded copies of their atom
  types, so MM molecules of the same types keep all bonded terms.

Each case runs in a fresh Python process, so every case starts from a clean
CHARMM state.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from tests.conftest import can_import_pycharmm

pytestmark = [
    pytest.mark.pycharmm,
    pytest.mark.skipif(
        not can_import_pycharmm(),
        reason="pycharmm / libcharmm not available",
    ),
]

_REPO_ROOT = Path(__file__).resolve().parents[3]

# One ethanol in RTF order C1 O1 HO1 H11 H12 C2 H21 H22 H23.
_ETOH_X = [0.0, -0.5, -1.45, -0.35, -0.35, 1.5, 1.9, 1.9, 1.9]
_ETOH_Y = [0.0, 1.3, 1.2, -0.55, -0.55, 0.0, 1.0, -0.5, -0.5]
_ETOH_Z = [0.0, 0.3, 0.1, 0.9, -0.9, 0.0, 0.0, 0.85, -0.85]

# Full CGenFF DIHE of one ethanol and the part left after the zeroed APPEND.
DIHE_FULL_ETOH = 3.23353
DIHE_AFTER_APPEND_ETOH = 0.28943
# Dihedrals per ethanol in the CGenFF RTF (autogenerated from bonds).
NPHI_ETOH = 12

_BONDED = ("BOND", "ANGL", "UREY", "DIHE", "IMPR", "CMAP")

_WORKER = r"""
import json
import sys
import warnings

import pandas as pd

import mmml.interfaces.pycharmmInterface.import_pycharmm  # noqa: F401
import pycharmm
import pycharmm.coor as coor
import pycharmm.energy as energy
import pycharmm.generate as gen
import pycharmm.read as read

from mmml.interfaces.pycharmmInterface.charmm_levels import charmm_relaxed_bomlev
from mmml.interfaces.pycharmmInterface.nbonds_config import read_cgenff_toppar

case = sys.argv[1]
spec = json.loads(sys.argv[2])
nmol = int(spec["nmol"])

read_cgenff_toppar()
n_aco = int(spec.get("n_aco", 0))
with charmm_relaxed_bomlev():
    read.sequence_string(" ".join(["ETOH"] * nmol + ["ACO"] * n_aco))
    gen.new_segment(seg_name="LIG", setup_ic=True)
xs, ys, zs = [], [], []
for m in range(nmol):
    xs += [v + 6.0 * m for v in spec["x"]]
    ys += list(spec["y"])
    zs += list(spec["z"])
pos = coor.get_positions()
pos.iloc[: len(xs)] = list(zip(xs, ys, zs))
coor.set_positions(pos)
if n_aco:
    # Acetone (shares CG331/HGA3 with ethanol, has an improper) built from IC.
    import pycharmm.ic as ic

    with charmm_relaxed_bomlev():
        ic.prm_fill(replace_all=False)
        ic.seed(nmol + 1, "C2", nmol + 1, "C1", nmol + 1, "C3")
        ic.build()
    pos = coor.get_positions()
    pos.iloc[len(xs) :, 1] += 6.0
    coor.set_positions(pos)

NBONDS = "NBONDS CUTNB 14.0 CTOFNB 12.0 CTONNB 10.0 NBXMOD 5 ATOM CDIE VATOM VSWITCH SWITCH"
TERMS = ("BOND", "ANGL", "UREY", "DIHE", "IMPR", "CMAP", "VDW", "ELEC")


natom = int(pycharmm.psf.get_natom())
n_ml_atoms = int(spec["n_ml_atoms"])


def ener():
    # READ PARAM resets the nonbond options; re-issue them before every ENER.
    pycharmm.lingo.charmm_script(NBONDS)
    energy.show()
    out = {k: float(energy.get_term_by_name(k)) for k in TERMS}
    # Bonded terms inside the ML and inside the MM region (no ML-MM bonds).
    for region, sel in (("ml", f"1:{n_ml_atoms}"), ("mm", f"{n_ml_atoms + 1}:{natom}")):
        if region == "mm" and n_ml_atoms >= natom:
            continue
        pycharmm.lingo.charmm_script(f"INTE SELE BYNUM {sel} END SELE BYNUM {sel} END")
        out[region] = {k: float(energy.get_term_by_name(k)) for k in TERMS[:6]}
    return out

ml = pycharmm.SelectAtoms(selection=tuple(i < n_ml_atoms for i in range(natom)))

from mmml.interfaces.pycharmmInterface.mlpot import block_terms
from mmml.interfaces.pycharmmInterface.mlpot.cgenff_prm_swap import (
    apply_zeroed_cgenff_params,
)

out = {"full": ener()}
if case == "delete_only":
    out["removed"] = block_terms.delete_ml_torsion_terms(ml)
    out["after"] = ener()
elif case == "append_only":
    apply_zeroed_cgenff_params(bonded_only=True)
    out["after"] = ener()
elif case == "append_then_delete":
    apply_zeroed_cgenff_params(bonded_only=True)
    out["append"] = ener()
    out["removed"] = block_terms.delete_ml_torsion_terms(ml, all_ml=n_ml_atoms >= natom)
    out["after"] = ener()
elif case.startswith("registration"):
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        tag = block_terms.zero_mlpot_psf_mm_terms(ml)
    out["tag"] = tag
    out["warnings"] = [str(w.message) for w in caught]
    out["after"] = ener()
    # All-ML registration also SKIPEs the bonded terms; lift it to check that
    # the zeroed params + PSF torsion deletion alone give zero.
    pycharmm.lingo.charmm_script("SKIPE NONE")
    out["after_noskip"] = ener()
    if case == "registration_restore":
        from mmml.interfaces.pycharmmInterface.mlpot.cgenff_prm_swap import (
            apply_full_cgenff_params,
        )

        apply_full_cgenff_params(force=True)
        out["restored"] = ener()
    elif case == "registration_twice":
        block_terms.zero_mlpot_psf_mm_terms(ml)
        out["again"] = ener()
else:
    raise SystemExit(f"unknown case {case}")
print("RESULT " + json.dumps(out), flush=True)
"""


def _run_case(case: str, *, nmol: int, n_ml_mol: int, n_aco: int = 0) -> dict:
    spec = {
        "nmol": nmol,
        "n_aco": n_aco,
        "n_ml_atoms": 9 * n_ml_mol,
        "x": _ETOH_X,
        "y": _ETOH_Y,
        "z": _ETOH_Z,
    }
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(
        p for p in (str(_REPO_ROOT), env.get("PYTHONPATH", "")) if p
    )
    env.setdefault("MMML_NO_CHARMM_MPI", "1")
    env.setdefault("MMML_NO_MPI_RERUN", "1")
    proc = subprocess.run(
        [sys.executable, "-c", _WORKER, case, json.dumps(spec)],
        cwd=str(_REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
        timeout=600,
    )
    lines = [ln for ln in proc.stdout.splitlines() if ln.startswith("RESULT ")]
    if proc.returncode != 0 or not lines:
        pytest.fail(
            f"CHARMM worker {case!r} failed (rc={proc.returncode})\n"
            f"stdout tail:\n{proc.stdout[-3000:]}\nstderr tail:\n{proc.stderr[-3000:]}"
        )
    return json.loads(lines[-1][len("RESULT ") :])


def test_full_cgenff_etoh_dihedral_reference() -> None:
    res = _run_case("append_only", nmol=1, n_ml_mol=1)
    assert res["full"]["DIHE"] == pytest.approx(DIHE_FULL_ETOH, abs=1e-4)


def test_zeroed_append_alone_leaves_multiterm_dihedral_terms() -> None:
    """Documents the CHARMM FLEX APPEND behaviour behind issue #217."""
    res = _run_case("append_only", nmol=1, n_ml_mol=1)
    after = res["after"]
    for key in ("BOND", "ANGL", "UREY", "IMPR"):
        assert after[key] == pytest.approx(0.0, abs=1e-8), key
    assert after["DIHE"] == pytest.approx(DIHE_AFTER_APPEND_ETOH, abs=1e-4)


def test_deleting_ml_torsions_keeps_nonbonded_and_other_bonded_terms() -> None:
    """Full CGenFF params: only DIHE changes; 1-4 pairs/exclusions unchanged."""
    res = _run_case("delete_only", nmol=2, n_ml_mol=1)
    full, after = res["full"], res["after"]
    assert res["removed"] == {"dihedrals": NPHI_ETOH, "impropers": 0, "cmaps": 0}
    assert full["DIHE"] - after["DIHE"] == pytest.approx(DIHE_FULL_ETOH, abs=1e-4)
    for key in ("BOND", "ANGL", "UREY", "IMPR", "VDW", "ELEC"):
        assert after[key] == pytest.approx(full[key], abs=1e-8), key


def test_all_ml_registration_zeroes_every_bonded_term() -> None:
    res = _run_case("registration", nmol=1, n_ml_mol=1)
    assert res["tag"] == "all"
    assert res["warnings"] == []
    for key in _BONDED:
        assert res["after"][key] == pytest.approx(0.0, abs=1e-8), key
        assert res["after_noskip"][key] == pytest.approx(0.0, abs=1e-8), key
    assert res["after_noskip"]["VDW"] == pytest.approx(res["after"]["VDW"], abs=1e-8)
    # ML charges are zeroed at registration.
    assert res["after"]["ELEC"] == pytest.approx(0.0, abs=1e-8)


def test_all_ml_append_then_delete_keeps_vdw_elec() -> None:
    res = _run_case("append_then_delete", nmol=1, n_ml_mol=1)
    assert res["removed"]["dihedrals"] == NPHI_ETOH
    assert res["append"]["DIHE"] == pytest.approx(DIHE_AFTER_APPEND_ETOH, abs=1e-4)
    for key in _BONDED:
        assert res["after"][key] == pytest.approx(0.0, abs=1e-8), key
    for key in ("VDW", "ELEC"):
        assert res["after"][key] == pytest.approx(res["append"][key], abs=1e-8), key


def test_hybrid_registration_deletes_only_ml_torsions() -> None:
    """2 ETOH, first ML: ML torsions go, the MM molecule keeps its PSF torsions."""
    res = _run_case("append_then_delete", nmol=2, n_ml_mol=1)
    assert res["removed"] == {"dihedrals": NPHI_ETOH, "impropers": 0, "cmaps": 0}
    # After the APPEND both molecules keep 0.28943; deleting the ML torsions
    # removes exactly the ML molecule's share.
    assert res["append"]["DIHE"] == pytest.approx(2 * DIHE_AFTER_APPEND_ETOH, abs=1e-4)
    assert res["after"]["DIHE"] == pytest.approx(DIHE_AFTER_APPEND_ETOH, abs=1e-4)
    for key in ("VDW", "ELEC"):
        assert res["after"][key] == pytest.approx(res["append"][key], abs=1e-8), key


def _assert_bonded(got: dict, want: dict | float, keys=_BONDED[:5]) -> None:
    for key in keys:
        ref = want if isinstance(want, float) else want[key]
        assert got[key] == pytest.approx(ref, abs=1e-6), key


def test_hybrid_registration_keeps_mm_bonded_terms() -> None:
    """#225: ML bonded terms zero, the MM molecule's terms exactly unchanged."""
    res = _run_case("registration", nmol=2, n_ml_mol=1)
    full, after = res["full"], res["after"]
    assert res["tag"] != "all"
    assert res["warnings"] == []
    _assert_bonded(after["ml"], 0.0)
    _assert_bonded(after["mm"], full["mm"])
    assert after["mm"]["DIHE"] == pytest.approx(DIHE_FULL_ETOH, abs=1e-4)
    assert after["VDW"] == pytest.approx(full["VDW"], abs=1e-8)
    # Only ML charges change ELEC; no SKIPE in the hybrid case.
    assert after["ELEC"] != pytest.approx(full["ELEC"], abs=1e-3)
    assert res["after_noskip"] == after


def test_hybrid_registration_other_molecule_types_keep_bonded_terms() -> None:
    """ML ethanol + MM ethanol + MM acetone (shares CG331/HGA3, has an IMPR)."""
    res = _run_case("registration", nmol=2, n_ml_mol=1, n_aco=1)
    full, after = res["full"], res["after"]
    assert full["mm"]["IMPR"] > 1e-4
    _assert_bonded(after["ml"], 0.0)
    _assert_bonded(after["mm"], full["mm"])
    assert after["VDW"] == pytest.approx(full["VDW"], abs=1e-8)


def test_hybrid_registration_restore_and_reregister() -> None:
    """Bonded restore brings ML bonds/angles back (not torsions); re-registration is idempotent."""
    res = _run_case("registration_restore", nmol=2, n_ml_mol=1)
    full, restored = res["full"], res["restored"]
    _assert_bonded(restored["ml"], full["ml"], keys=("BOND", "ANGL", "UREY"))
    assert restored["ml"]["DIHE"] == pytest.approx(0.0, abs=1e-8)
    _assert_bonded(restored["mm"], full["mm"])
    assert restored["VDW"] == pytest.approx(full["VDW"], abs=1e-8)

    res = _run_case("registration_twice", nmol=2, n_ml_mol=1)
    assert res["again"] == res["after"]
