"""Lattice energy and sublimation enthalpy of a molecular crystal under CGenFF.

This deliberately does not go through ``mmml md-system --evaluate-npz``. That
path resolves a periodic cell to a single cubic side
(:func:`mmml.cli.run.md_stage_summary.cubic_box_side_from_cell`), which is fine
for the liquid boxes it was written for and wrong for a crystal: the acetone
Pbca cell (9.17 x 7.53 x 21.25 A) would be run as a 12.65 A cube. Everything
here therefore carries the full ``(3, 3)`` cell.

The energy is an *explicit lattice sum*, not a minimum-image sum. The minimum
image convention caps the cutoff at half the shortest cell edge -- 3.77 A for
that acetone cell -- which is far too short for either dispersion or the
real-space Ewald split. Summing over lattice shifts instead decouples the
cutoff from the cell size, at a cost that is irrelevant for a unit cell of a
few hundred atoms.

What is computed is the *intermolecular* energy per molecule, so bonded and
intramolecular nonbonded terms cancel exactly against an isolated molecule held
at the same geometry. That makes the lattice energy directly comparable to a
gas-phase reference without ever evaluating one, and it is why the sublimation
enthalpy below needs no separate gas calculation.

Sublimation enthalpy follows the standard rigid-molecule result

    dH_sub(T) = -E_latt - 2RT

whose ``-2RT`` is the difference between the gas-phase ``4RT`` (3/2 RT
translation + 3/2 RT rotation + RT for pV) and the ``6RT`` carried classically
by the six rigid-body lattice modes that replace them in the crystal. It
neglects the difference in intramolecular vibration between phases and all
quantum (zero-point) corrections, both of which are small for a rigid molecule
but neither of which is zero.

References: Allen & Tildesley, *Computer Simulation of Liquids*, 2nd ed., ch. 2
(tail corrections) and ch. 12 (Ewald); Gavezzotti, *Acc. Chem. Res.* 27, 309
(1994) for the ``-2RT`` convention.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import numpy as np

from mmml.models.cgenff_mm import COULOMB_CONSTANT, sigma_to_rmin_half

__all__ = [
    "GAS_CONSTANT_KCAL_MOL_K",
    "MolecularCell",
    "LatticeEnergyResult",
    "build_molecular_cell",
    "unwrap_molecules",
    "molecular_reach_A",
    "lattice_shift_vectors",
    "periodic_coulomb_energy",
    "crystal_lattice_energy",
    "sublimation_enthalpy_kcal_mol",
    "KCAL_MOL_TO_KJ_MOL",
]

# CODATA 2018 gas constant expressed in the CHARMM energy unit.
GAS_CONSTANT_KCAL_MOL_K: float = 1.987204259e-3
KCAL_MOL_TO_KJ_MOL: float = 4.184


@dataclass(frozen=True)
class MolecularCell:
    """One periodic cell split into whole molecules with CGenFF parameters.

    ``positions`` are *unwrapped*: every molecule is contiguous in space and
    each molecular centroid lies inside the cell. Bonded geometry can therefore
    be read straight off the array, and lattice images are generated by shifting
    the whole set rather than per atom.
    """

    positions: np.ndarray  # (n_atoms, 3) Angstrom
    atomic_numbers: np.ndarray  # (n_atoms,)
    cell: np.ndarray  # (3, 3) Angstrom, rows are lattice vectors
    mol_id: np.ndarray  # (n_atoms,) molecule index
    type_idx: np.ndarray  # (n_atoms,) index into the CGenFF master tables
    charges: np.ndarray  # (n_atoms,) e
    residues: tuple[str, ...]  # CGenFF RESI name per molecule

    @property
    def n_molecules(self) -> int:
        return len(self.residues)

    @property
    def volume_A3(self) -> float:
        return float(abs(np.linalg.det(self.cell)))

    def density_g_cm3(self, masses_amu: np.ndarray | None = None) -> float:
        from ase.data import atomic_masses

        m = atomic_masses[self.atomic_numbers] if masses_amu is None else np.asarray(masses_amu)
        return float(np.sum(m) / self.volume_A3 / 0.6022140857)


@dataclass(frozen=True)
class LatticeEnergyResult:
    """Intermolecular energy per molecule and its decomposition (kcal/mol)."""

    e_lattice: float
    e_lj: float
    e_lj_tail: float
    e_coulomb: float
    n_molecules: int
    cutoff_A: float
    n_lattice_shifts: int
    n_kvectors: int
    ewald_alpha: float
    density_g_cm3: float
    cell_lengths_A: tuple[float, float, float]
    residues: tuple[str, ...]

    def sublimation_enthalpy(self, temperature_K: float) -> float:
        return sublimation_enthalpy_kcal_mol(self.e_lattice, temperature_K)


def _mic_displacements(delta: np.ndarray, cell: np.ndarray) -> np.ndarray:
    """Minimum-image displacements for ``delta`` under ``cell`` (rows = vectors)."""
    frac = delta @ np.linalg.inv(cell)
    return (frac - np.round(frac)) @ cell


def unwrap_molecules(
    positions: np.ndarray,
    atomic_numbers: np.ndarray,
    cell: np.ndarray,
    *,
    bond_scale: float = 1.3,
) -> tuple[np.ndarray, np.ndarray]:
    """Split a periodic cell into molecules and make each one contiguous.

    Returns ``(mol_id, unwrapped_positions)``. Connectivity is covalent-radius
    based on minimum-image distances, so molecules that straddle a cell face are
    recognised as one molecule and then rebuilt on whichever side keeps them
    whole. Each molecule is finally translated by a lattice vector so its
    centroid sits inside the cell, which bounds how far the atoms of one image
    can reach and therefore how many lattice shifts the sums below need.
    """
    from ase.data import covalent_radii

    pos = np.asarray(positions, dtype=np.float64)
    z = np.asarray(atomic_numbers, dtype=int)
    cell = np.asarray(cell, dtype=np.float64).reshape(3, 3)
    n = len(pos)

    delta = pos[None, :, :] - pos[:, None, :]
    disp = _mic_displacements(delta.reshape(-1, 3), cell).reshape(n, n, 3)
    dist = np.linalg.norm(disp, axis=-1)
    r_cov = covalent_radii[z]
    adjacent = dist < bond_scale * (r_cov[:, None] + r_cov[None, :])
    np.fill_diagonal(adjacent, False)

    mol_id = np.full(n, -1, dtype=np.int64)
    unwrapped = np.array(pos, dtype=np.float64, copy=True)
    current = 0
    for seed in range(n):
        if mol_id[seed] >= 0:
            continue
        mol_id[seed] = current
        queue = [seed]
        while queue:
            i = queue.pop(0)
            for j in np.flatnonzero(adjacent[i]):
                if mol_id[j] >= 0:
                    continue
                mol_id[j] = current
                # Rebuild j relative to i, so a bond never spans the cell.
                unwrapped[j] = unwrapped[i] + disp[i, j]
                queue.append(int(j))
        current += 1

    inv_cell = np.linalg.inv(cell)
    for m in range(current):
        sel = mol_id == m
        centroid = unwrapped[sel].mean(axis=0)
        shift = np.floor(centroid @ inv_cell) @ cell
        unwrapped[sel] -= shift
    return mol_id, unwrapped


def _assign_cgenff_parameters(
    positions: np.ndarray,
    atomic_numbers: np.ndarray,
    mol_id: np.ndarray,
    *,
    prm_path: Path | str | None = None,
    rtf_path: Path | str | None = None,
) -> tuple[np.ndarray, np.ndarray, tuple[str, ...], np.ndarray, np.ndarray]:
    """Type every molecule against CGenFF; no live CHARMM session required."""
    from mmml.data.cgenff_dataset import (
        DEF_PRM_PATH,
        DEF_RTF_PATH,
        load_reference,
        match_cgenff_template,
    )

    ref = load_reference(
        str(prm_path) if prm_path is not None else DEF_PRM_PATH,
        str(rtf_path) if rtf_path is not None else DEF_RTF_PATH,
    )
    type_idx = np.zeros(len(positions), dtype=np.int32)
    charges = np.zeros(len(positions), dtype=np.float64)
    residues: list[str] = []
    for m in range(int(mol_id.max()) + 1):
        sel = np.flatnonzero(mol_id == m)
        resi, types_m, charges_m = match_cgenff_template(
            ref, atomic_numbers[sel], positions[sel]
        )
        type_idx[sel] = types_m
        charges[sel] = charges_m
        residues.append(resi)
    return type_idx, charges, tuple(residues), ref.sigmas, ref.epsilons


def build_molecular_cell(
    positions: np.ndarray,
    atomic_numbers: np.ndarray,
    cell: np.ndarray,
    *,
    prm_path: Path | str | None = None,
    rtf_path: Path | str | None = None,
) -> tuple[MolecularCell, np.ndarray, np.ndarray]:
    """Unwrap into molecules and attach CGenFF types/charges.

    Returns ``(molecular_cell, master_sigmas, master_epsilons)``.
    """
    mol_id, unwrapped = unwrap_molecules(positions, atomic_numbers, cell)
    type_idx, charges, residues, sigmas, epsilons = _assign_cgenff_parameters(
        unwrapped, np.asarray(atomic_numbers, dtype=int), mol_id,
        prm_path=prm_path, rtf_path=rtf_path,
    )
    mcell = MolecularCell(
        positions=unwrapped,
        atomic_numbers=np.asarray(atomic_numbers, dtype=int),
        cell=np.asarray(cell, dtype=np.float64).reshape(3, 3),
        mol_id=mol_id,
        type_idx=type_idx,
        charges=charges,
        residues=residues,
    )
    return mcell, sigmas, epsilons


def molecular_reach_A(positions: np.ndarray, mol_id: np.ndarray) -> float:
    """Largest distance from any atom to its own molecule's centroid."""
    reach = 0.0
    for m in range(int(mol_id.max()) + 1):
        block = np.asarray(positions)[mol_id == m]
        reach = max(reach, float(np.linalg.norm(block - block.mean(axis=0), axis=1).max()))
    return reach


def lattice_shift_vectors(
    cell: np.ndarray,
    cutoff_A: float,
    *,
    reach_A: float = 0.0,
) -> np.ndarray:
    """Lattice translations covering every pair within ``cutoff_A``.

    ``reach_A`` is how far an atom can sit from its own molecular centroid;
    since :func:`unwrap_molecules` only guarantees the *centroids* are inside
    the cell, images must be generated far enough out to catch the overhang on
    both sides. The per-axis bound uses the perpendicular spacing ``V / |a_j x
    a_k|``, not the edge length, so it stays correct for skewed cells.
    """
    cell = np.asarray(cell, dtype=np.float64).reshape(3, 3)
    volume = float(abs(np.linalg.det(cell)))
    if volume <= 0.0:
        raise ValueError(f"non-positive cell volume {volume}")
    span = float(cutoff_A) + 2.0 * float(reach_A)
    n_max = []
    for axis in range(3):
        other = cell[[i for i in range(3) if i != axis]]
        spacing = volume / np.linalg.norm(np.cross(other[0], other[1]))
        n_max.append(int(np.ceil(span / spacing)))
    ranges = [np.arange(-n, n + 1) for n in n_max]
    grid = np.stack(np.meshgrid(*ranges, indexing="ij"), axis=-1).reshape(-1, 3)
    return grid.astype(np.float64) @ cell


def _pair_tables(
    mcell: MolecularCell,
    master_sigmas: np.ndarray,
    master_epsilons: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Per-pair ``(Rmin_ij, eps_ij)`` under the CHARMM combining rules."""
    sig = np.asarray(master_sigmas)[mcell.type_idx]
    eps = np.asarray(master_epsilons)[mcell.type_idx]
    rmin_half = np.asarray(sigma_to_rmin_half(sig))
    pair_rmin = rmin_half[:, None] + rmin_half[None, :]  # arithmetic
    pair_eps = np.sqrt(np.maximum(eps[:, None] * eps[None, :], 0.0))  # geometric
    return pair_rmin, pair_eps


def _lj_real_space(
    mcell: MolecularCell,
    pair_rmin: np.ndarray,
    pair_eps: np.ndarray,
    shifts: np.ndarray,
    cutoff_A: float,
) -> float:
    """Explicit lattice sum of the CHARMM LJ over all intermolecular pairs."""
    pos = mcell.positions
    same_molecule = mcell.mol_id[:, None] == mcell.mol_id[None, :]
    total = 0.0
    for shift in shifts:
        is_home = not np.any(shift)
        delta = (pos[None, :, :] + shift) - pos[:, None, :]
        r = np.linalg.norm(delta, axis=-1)
        keep = r < cutoff_A
        # In the home cell a molecule does not interact with itself; in every
        # other image it does, and that self-image term is part of the lattice
        # energy rather than an intramolecular one.
        keep &= ~same_molecule if is_home else r > 0.0
        if not np.any(keep):
            continue
        r_safe = np.where(keep, np.maximum(r, 1e-10), 1.0)
        r6 = (pair_rmin / r_safe) ** 6
        e = pair_eps * (r6 * r6 - 2.0 * r6)
        total += 0.5 * float(np.sum(np.where(keep, e, 0.0)))
    return total


def _lj_tail_correction(
    mcell: MolecularCell,
    pair_rmin: np.ndarray,
    pair_eps: np.ndarray,
    cutoff_A: float,
) -> float:
    """Isotropic correction for LJ pairs beyond the cutoff.

    ``E_tail = (2*pi/V) * sum_ij int_rc^inf u_ij(r) r^2 dr`` with ``g(r) = 1``
    assumed outside ``rc``. The assumption is not strictly true in a crystal,
    but by ``rc`` the attractive tail is smooth enough that the alternative --
    an even longer cutoff -- changes the answer by less than the correction
    itself. Reported separately so the approximation stays visible.
    """
    rc = float(cutoff_A)
    integral = pair_eps * (
        pair_rmin**12 / (9.0 * rc**9) - 2.0 * pair_rmin**6 / (3.0 * rc**3)
    )
    return float(2.0 * np.pi / mcell.volume_A3 * np.sum(integral))


def periodic_coulomb_energy(
    positions: np.ndarray,
    charges: np.ndarray,
    cell: np.ndarray,
    *,
    cutoff_A: float = 12.0,
    excluded_pairs: np.ndarray | None = None,
    shifts: np.ndarray | None = None,
    accuracy_exponent: float = 3.5,
) -> tuple[float, float, int]:
    """Ewald Coulomb energy (kcal/mol) of one cell's contents. ``(E, alpha, n_k)``.

    ``excluded_pairs`` is an ``(n, 2)`` index array of pairs that must not
    interact at all -- here, atoms of the same molecule in the same image. They
    are dropped from the real-space sum, and their implicit ``erf(alpha r)/r``
    contribution to the reciprocal sum is subtracted, so their net contribution
    is exactly zero rather than merely screened.

    Tinfoil (conducting) boundary conditions: no surface dipole term. That is
    the standard convention and costs nothing for a centrosymmetric cell, which
    carries no net dipole in the first place.
    """
    import jax.numpy as jnp
    from scipy.special import erfc

    from mmml.interfaces.pycharmmInterface.ewald_native import (
        build_kspace_integers,
        default_ewald_alpha,
        ewald_exclusion_correction,
        ewald_reciprocal_energy,
        ewald_self_energy,
    )

    pos = np.asarray(positions, dtype=np.float64)
    q = np.asarray(charges, dtype=np.float64)
    cell = np.asarray(cell, dtype=np.float64).reshape(3, 3)

    net = float(np.sum(q))
    if abs(net) > 1e-6:
        raise ValueError(
            f"Ewald without a neutralising background requires a neutral cell; "
            f"charges sum to {net:+.3e} e"
        )

    alpha = default_ewald_alpha(cutoff_A, accuracy_exponent=accuracy_exponent)
    n_int = build_kspace_integers(cell, alpha, accuracy_exponent=accuracy_exponent)
    if shifts is None:
        shifts = lattice_shift_vectors(cell, cutoff_A, reach_A=0.0)

    excluded = np.zeros((len(pos), len(pos)), dtype=bool)
    if excluded_pairs is not None and len(excluded_pairs):
        idx = np.asarray(excluded_pairs, dtype=int)
        excluded[idx[:, 0], idx[:, 1]] = True
        excluded[idx[:, 1], idx[:, 0]] = True
    np.fill_diagonal(excluded, True)

    qq = q[:, None] * q[None, :]
    e_real = 0.0
    for shift in shifts:
        is_home = not np.any(shift)
        delta = (pos[None, :, :] + shift) - pos[:, None, :]
        r = np.linalg.norm(delta, axis=-1)
        keep = r < cutoff_A
        # Exclusions apply only in the home image: an atom does interact with
        # its own periodic images, and so does the rest of its molecule.
        keep &= ~excluded if is_home else r > 0.0
        if not np.any(keep):
            continue
        r_safe = np.where(keep, np.maximum(r, 1e-10), 1.0)
        e_real += 0.5 * float(np.sum(np.where(keep, qq * erfc(alpha * r_safe) / r_safe, 0.0)))

    excl_i, excl_j = np.triu_indices(len(pos), k=1)
    keep_excl = excluded[excl_i, excl_j]
    excl_i = excl_i[keep_excl].astype(np.int32)
    excl_j = excl_j[keep_excl].astype(np.int32)

    r_jnp = jnp.asarray(pos)
    q_jnp = jnp.asarray(q)
    cell_jnp = jnp.asarray(cell)
    e_recip = float(ewald_reciprocal_energy(r_jnp, q_jnp, cell_jnp, n_int, alpha))
    e_self = float(ewald_self_energy(q_jnp, alpha))
    e_excl = float(
        ewald_exclusion_correction(
            r_jnp, q_jnp, cell_jnp, jnp.asarray(excl_i), jnp.asarray(excl_j), alpha
        )
    )
    total = COULOMB_CONSTANT * (e_real + e_recip + e_self + e_excl)
    return total, float(alpha), int(n_int.shape[0])


def _intramolecular_pairs(mol_id: np.ndarray) -> np.ndarray:
    """All ``(i, j)`` index pairs sharing a molecule, as an ``(n, 2)`` array."""
    iu, ju = np.triu_indices(len(mol_id), k=1)
    same = mol_id[iu] == mol_id[ju]
    return np.stack([iu[same], ju[same]], axis=1)


def crystal_lattice_energy(
    positions: np.ndarray,
    atomic_numbers: np.ndarray,
    cell: np.ndarray,
    *,
    cutoff_A: float = 12.0,
    sigma_scale: Sequence[float] | np.ndarray | None = None,
    epsilon_scale: Sequence[float] | np.ndarray | None = None,
    prm_path: Path | str | None = None,
    rtf_path: Path | str | None = None,
    masses_amu: np.ndarray | None = None,
) -> LatticeEnergyResult:
    """Intermolecular CGenFF energy per molecule for a periodic crystal.

    ``sigma_scale`` / ``epsilon_scale`` are the per-CGenFF-type multipliers
    learned by hybrid training (see :mod:`mmml.models.mm_lj_scales`); passing
    them evaluates the same crystal under the trained parameters, which turns
    the sublimation enthalpy into a validation observable for that fit.
    """
    mcell, sigmas, epsilons = build_molecular_cell(
        positions, atomic_numbers, cell, prm_path=prm_path, rtf_path=rtf_path
    )
    if sigma_scale is not None or epsilon_scale is not None:
        from mmml.models.mm_lj_scales import apply_mm_lj_scales

        scaled = apply_mm_lj_scales(sigmas, epsilons, sigma_scale, epsilon_scale)
        sigmas, epsilons = np.asarray(scaled[0]), np.asarray(scaled[1])

    reach = molecular_reach_A(mcell.positions, mcell.mol_id)
    shifts = lattice_shift_vectors(mcell.cell, cutoff_A, reach_A=reach)

    pair_rmin, pair_eps = _pair_tables(mcell, sigmas, epsilons)
    e_lj = _lj_real_space(mcell, pair_rmin, pair_eps, shifts, cutoff_A)
    e_tail = _lj_tail_correction(mcell, pair_rmin, pair_eps, cutoff_A)
    e_coulomb, alpha, n_k = periodic_coulomb_energy(
        mcell.positions,
        mcell.charges,
        mcell.cell,
        cutoff_A=cutoff_A,
        excluded_pairs=_intramolecular_pairs(mcell.mol_id),
        shifts=shifts,
    )

    z = mcell.n_molecules
    lengths = np.linalg.norm(mcell.cell, axis=1)
    return LatticeEnergyResult(
        e_lattice=(e_lj + e_tail + e_coulomb) / z,
        e_lj=e_lj / z,
        e_lj_tail=e_tail / z,
        e_coulomb=e_coulomb / z,
        n_molecules=z,
        cutoff_A=float(cutoff_A),
        n_lattice_shifts=int(len(shifts)),
        n_kvectors=n_k,
        ewald_alpha=alpha,
        density_g_cm3=mcell.density_g_cm3(masses_amu),
        cell_lengths_A=(float(lengths[0]), float(lengths[1]), float(lengths[2])),
        residues=mcell.residues,
    )


def sublimation_enthalpy_kcal_mol(
    lattice_energy_kcal_mol: float,
    temperature_K: float,
) -> float:
    """``dH_sub = -E_latt - 2RT`` for a rigid molecule (see module docstring)."""
    return -float(lattice_energy_kcal_mol) - 2.0 * GAS_CONSTANT_KCAL_MOL_K * float(
        temperature_K
    )
