residue: meoh 
density: 792.0
side_length: 35.0

qm:
  basis: cc-pVDZ
  xc: PBE0
  optimize: true
  hessian: true
  thermo: true
  gradient: true
  harmonic: true

md:
  temperatures: [300, 300, 300]
  pressures: [1.0, 1.0, 1.0]
  integrator: Langevin
  schedule: [minimization, equilibration, NPT]
  steps: 1000000

cluster:
  n_find: 2
  stride: 1

