#!/usr/bin/env python3
"""Zero bonded and nonbonded force constants in a CHARMM parameter (.prm) file.

Preserves atom types, equilibrium geometry (r0, theta0, dihedral phase/multiplicity),
masses, and comments. Intended for MLpot runs where CHARMM MM terms should contribute
no energy but topology lookup must remain intact.

Usage:
    python scripts/zero_charmm_prm.py \\
        mmml/data/charmm/par_all36_cgenff.prm \\
        mmml/data/charmm/zeroed_par_all36_cgenff.prm
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from mmml.interfaces.pycharmmInterface.charmm_prm_zero import (
    bonded_only_prm_text,
    zero_prm_file,
    zero_prm_line,
    zero_prm_text,
)

__all__ = [
    "bonded_only_prm_text",
    "zero_prm_file",
    "zero_prm_line",
    "zero_prm_text",
]


def extract_bonded_prm_file(src: Path, dst: Path) -> None:
    text = src.read_text(encoding="utf-8", errors="replace")
    header = (
        "*  BONDED COPY — BOND/ANGL/DIHE/IMPR only (append-safe; no NONBONDED/HBOND)\n"
        f"*  Source: {src.name}\n"
        f"*  Generated by: {Path(__file__).name}\n"
        "*  --------------------------------------------------------------------------  *\n"
    )
    bonded = header + bonded_only_prm_text(text, zero_constants=False)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(bonded, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Input CHARMM .prm file")
    parser.add_argument("destination", type=Path, help="Output zeroed .prm file")
    parser.add_argument(
        "--bonded-only",
        action="store_true",
        help="Zero bonded terms only; omit NONBONDED/NBFIX/HBOND (append-safe)",
    )
    parser.add_argument(
        "--extract-bonded-only",
        action="store_true",
        help="Copy bonded sections only without zeroing (append-safe MM restore)",
    )
    args = parser.parse_args(argv)
    if not args.source.is_file():
        print(f"error: source not found: {args.source}", file=sys.stderr)
        return 1
    if args.extract_bonded_only and args.bonded_only:
        print("error: use only one of --bonded-only or --extract-bonded-only", file=sys.stderr)
        return 1
    if args.extract_bonded_only:
        extract_bonded_prm_file(args.source, args.destination)
    else:
        zero_prm_file(args.source, args.destination, bonded_only=args.bonded_only)
    print(f"Wrote {args.destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
