##################################
# Do all QM Calculations
##################################

rule qm_clusters:
    input:  "clusters-octanol.dat"
    output: "qm-clusters.log"
    
    run:
        flags = [
            f"--{flag}"
            for flag, enabled in config["qm"].items()
            if enabled and flag in [ "gradient", ]
        ]
        flags_str = " ".join(flags)

        shell(
            f"""hostname &&
            bash ~/mmml/setup/install.sh &&
            module load cudnn && for XYZ in $(cat {input}); do CUDA_DEVICES="0" uv run python ~/mmml/mmml/pyscf4gpuInterface/calcs.py --output $XYZ.npz --mol $XYZ  --xc {config['qm']['xc']} --basis {config['qm']['basis']} {flags_str} > $XYZ.log; done"""
        )
