#!/usr/bin/env python3
"""Turn ``checkpoint_triage.py`` metrics into a ranked scoreboard (CSV + Markdown).

Ranking rule
------------
Physics gates come first, dataset error only breaks ties. A checkpoint that
fails ``physics`` or ``smoothness`` is never ranked above one that passes,
regardless of MAE -- that ordering is the whole point of the exercise. Tiers
that were skipped do not count as passes and are shown as ``-``.

Example::

    python workflows/validation_campaign/scripts/checkpoint_scoreboard.py \\
        --metrics artifacts/validation_campaign/<run>/checkpoint.triage/metrics.json \\
        --output-dir docs/images/checkpoints --markdown docs/checkpoint-scoreboard.md
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

GATES = ("load", "physics", "smoothness")
SYMBOL = {"pass": "pass", "fail": "FAIL", "skipped": "-"}


def _status(row: dict[str, Any], tier: str) -> str:
    return row.get(tier, {}).get("status", "skipped") if isinstance(row.get(tier), dict) else "skipped"


def _metric(row: dict[str, Any], tier: str, key: str) -> Any:
    node = row.get(tier)
    return node.get(key) if isinstance(node, dict) else None


def rank(results: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    for name, row in results.items():
        gates = {g: _status(row, g) for g in GATES}
        n_failed = sum(1 for s in gates.values() if s == "fail")
        e_mae = _metric(row, "dataset", "energy_mae")
        f_mae = _metric(row, "dataset", "forces_mae")
        rows.append(
            {
                "checkpoint": name,
                "load": SYMBOL[gates["load"]],
                "physics": SYMBOL[gates["physics"]],
                "smoothness": SYMBOL[gates["smoothness"]],
                "energy_mae": e_mae,
                "forces_mae": f_mae,
                "gates_failed": n_failed,
                "wall_s": row.get("_wall_s"),
            }
        )
    # Gates dominate; energy MAE breaks ties (None sorts last).
    rows.sort(key=lambda r: (r["gates_failed"],
                             r["energy_mae"] if r["energy_mae"] is not None else float("inf"),
                             r["checkpoint"]))
    for i, r in enumerate(rows, 1):
        r["rank"] = i
    return rows


def to_markdown(rows: list[dict[str, Any]], *, glob: str | None) -> str:
    out = [
        "# Checkpoint scoreboard",
        "",
        "Generated by `workflows/validation_campaign/scripts/checkpoint_scoreboard.py`.",
        "",
        "Physics gates rank above dataset error: a checkpoint that fails `physics` or",
        "`smoothness` is never placed above one that passes, whatever its MAE. `-` means",
        "the tier was **skipped**, not passed.",
        "",
    ]
    if glob:
        out += [f"Candidates: `{glob}`", ""]
    out += [
        "| # | Checkpoint | load | physics | smoothness | energy MAE | forces MAE |",
        "|---|------------|------|---------|------------|-----------:|-----------:|",
    ]
    fmt = lambda v: "—" if v is None else f"{v:.4g}"  # noqa: E731
    for r in rows:
        out.append(
            f"| {r['rank']} | `{r['checkpoint']}` | {r['load']} | {r['physics']} | "
            f"{r['smoothness']} | {fmt(r['energy_mae'])} | {fmt(r['forces_mae'])} |"
        )
    out += ["", "## How to read this", ""]
    if all(r["energy_mae"] is None for r in rows):
        out.append(
            "No dataset tier ran, so **this table cannot tell you which checkpoint is "
            "most accurate** — only which ones are free of the pathologies the physics "
            "gates detect. Supply `--test-extxyz` and `--cache-dir` to rank on error."
        )
    else:
        out.append(
            "Ranking is by gates first, then energy MAE. Where the top two differ only "
            "in MAE, prefer the earlier epoch: it has had less opportunity to overfit "
            "into the sharp features that MD finds."
        )
    return "\n".join(out) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--metrics", type=Path, required=True, help="metrics.json from checkpoint_triage.py")
    p.add_argument("--csv", type=Path, help="write the ranked table here")
    p.add_argument("--markdown", type=Path, help="write a Markdown scoreboard here")
    p.add_argument("--glob", help="candidate glob, recorded in the Markdown header")
    args = p.parse_args()

    if not args.metrics.is_file():
        raise SystemExit(f"no metrics file: {args.metrics}")
    results = json.loads(args.metrics.read_text())
    if not results:
        raise SystemExit(f"{args.metrics} is empty -- did the triage run?")

    rows = rank(results)

    if args.csv:
        args.csv.parent.mkdir(parents=True, exist_ok=True)
        cols = ["rank", "checkpoint", "load", "physics", "smoothness",
                "energy_mae", "forces_mae", "gates_failed", "wall_s"]
        with args.csv.open("w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=cols)
            w.writeheader()
            w.writerows(rows)
        print(f"checkpoint_scoreboard: wrote {args.csv}")

    md = to_markdown(rows, glob=args.glob)
    if args.markdown:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text(md, encoding="utf-8")
        print(f"checkpoint_scoreboard: wrote {args.markdown}")
    else:
        sys.stdout.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
