"""Render and run local job scripts (local_laptop, local_computer).

Produces the same request/provenance/status/proof receipts as the Slurm path, so
``campaign.py status`` cannot distinguish a laptop receipt from a cluster one --
only a proven task from an unproven one.
"""

from __future__ import annotations

import shlex
import subprocess
from pathlib import Path
from typing import Any

import campaign_lib as lib


def render(
    cfg: dict[str, Any],
    task_id: str,
    task: dict[str, Any],
    env: dict[str, Any],
    run_id: str,
) -> Path:
    out = lib.output_dir(cfg, run_id, task_id, env["name"])
    out.mkdir(parents=True, exist_ok=True)

    rel = lib.rel_output_dir(cfg, run_id, task_id, env["name"])
    command = lib.render_command(task, rel, python='"$MMML_PYTHON"')
    lib.write_json(
        out / "request.json", lib.request_payload(task_id, task, env, run_id, command)
    )

    quoted_out = shlex.quote(str(rel))
    script = "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# GENERATED by run_local.py for {task_id} @ {env['name']} -- do not edit.",
            "set -uo pipefail",
            "",
            f"cd {lib.repo_root_shell(env)}",
            "",
            "source scripts/resolve_mmml_env.sh",
            'mmml_resolve_env "$PWD"',
            lib.shell_exports(env),
            "",
            f"mkdir -p {quoted_out}",
            '"$MMML_PYTHON" workflows/validation_campaign/scripts/finalize_task.py \\',
            f"  --output-dir {quoted_out} --phase running",
            "",
            "set +e",
            f"{command} \\",
            f"  > {shlex.quote(str(rel / 'stdout.log'))} \\",
            f"  2> {shlex.quote(str(rel / 'stderr.log'))}",
            "task_rc=$?",
            "set -e",
            "",
            '"$MMML_PYTHON" workflows/validation_campaign/scripts/finalize_task.py \\',
            f'  --output-dir {quoted_out} --phase finished --exit-code "$task_rc"',
            "",
            "exit $task_rc",
            "",
        ]
    )

    path = out / "job.sh"
    path.write_text(script, encoding="utf-8")
    path.chmod(0o755)
    return path


def run(
    cfg: dict[str, Any],
    task_id: str,
    task: dict[str, Any],
    env: dict[str, Any],
    run_id: str,
) -> int:
    path = render(cfg, task_id, task, env, run_id)
    proc = subprocess.run(["bash", str(path)], cwd=lib.REPO)
    return proc.returncode
