"""Render and run local job scripts (local_laptop, local_computer).

Produces the same request/provenance/status/proof layout as the Slurm path, so
``campaign.py status`` cannot tell the difference between a laptop receipt and a
cluster receipt -- only between a proven task and an unproven one.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import campaign_lib as lib
from campaign_lib import Campaign, Environment, Task

SCRIPT_NAME = "job.sh"


def render_local_script(
    campaign: Campaign, task: Task, environment: Environment, run_id: str
) -> tuple[Path, str]:
    out_dir = lib.output_dir(campaign, run_id, task.task_id, environment.name)
    out_dir.mkdir(parents=True, exist_ok=True)

    command = lib.render_command(task, campaign, out_dir)
    lib.write_request(out_dir, task, campaign, environment, command)

    exports = "\n".join(
        f'export {key}="{value}"' for key, value in (environment.environment or {}).items()
    )

    script = f"""#!/usr/bin/env bash
# GENERATED by workflows/validation_campaign/scripts/run_local.py -- do not edit by hand.
# task: {task.task_id}   goal: {task.goal}   tier: {task.tier}   env: {environment.name}
set -uo pipefail

REPO_ROOT="{lib.REPO_ROOT}"
cd "$REPO_ROOT"

OUT_DIR="{out_dir}"
mkdir -p "$OUT_DIR"

source "$REPO_ROOT/scripts/resolve_mmml_env.sh"
mmml_resolve_env "$REPO_ROOT"

{exports}

export MMML_CAMPAIGN_RUN_ID="{run_id}"
export MMML_CAMPAIGN_TASK="{task.task_id}"
export MMML_CAMPAIGN_ENV="{environment.name}"
export PYTHONPATH="$REPO_ROOT/workflows/validation_campaign/scripts:${{PYTHONPATH:-}}"

"$MMML_PYTHON" workflows/validation_campaign/scripts/record_status.py \\
  --output-dir "$OUT_DIR" --phase running --environment {environment.name}

set +e
{command.replace("python ", '"$MMML_PYTHON" ', 1)} \\
  > >(tee "$OUT_DIR/stdout.log") 2> >(tee "$OUT_DIR/stderr.log" >&2)
EXIT_CODE=$?
set -e

"$MMML_PYTHON" workflows/validation_campaign/scripts/record_status.py \\
  --output-dir "$OUT_DIR" --phase finished --exit-code "$EXIT_CODE" \\
  --environment {environment.name}

exit "$EXIT_CODE"
"""

    path = out_dir / SCRIPT_NAME
    path.write_text(script)
    path.chmod(0o755)
    return path, script


def run(campaign: Campaign, task: Task, environment: Environment, run_id: str) -> int:
    path, _ = render_local_script(campaign, task, environment, run_id)
    proc = subprocess.run(["bash", str(path)], cwd=lib.REPO_ROOT)
    return proc.returncode
