"""Render and submit Slurm job scripts for campaign tasks (pcbach/scicore/pcstudix).

The generated script is written into the task's proof directory and is the exact
thing that runs. ``prepare`` stops there so it can be inspected; ``submit`` calls
sbatch on the same file.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import campaign_lib as lib
from campaign_lib import Campaign, Environment, Task

SCRIPT_NAME = "job.sbatch"


def render_slurm_script(
    campaign: Campaign, task: Task, environment: Environment, run_id: str
) -> tuple[Path, str]:
    out_dir = lib.output_dir(campaign, run_id, task.task_id, environment.name)
    out_dir.mkdir(parents=True, exist_ok=True)

    command = lib.render_command(task, campaign, out_dir)
    lib.write_request(out_dir, task, campaign, environment, command)

    job_name = f"vc-{task.task_id.replace('.', '-')}"
    cpus = environment.cpus_per_task or environment.cpus

    directives = [
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --output={out_dir}/slurm-%j.out",
        f"#SBATCH --error={out_dir}/slurm-%j.err",
        f"#SBATCH --nodes={environment.nodes}",
        f"#SBATCH --ntasks={environment.ntasks}",
        f"#SBATCH --cpus-per-task={cpus}",
        f"#SBATCH --time={environment.runtime_min // 60:02d}:{environment.runtime_min % 60:02d}:00",
    ]
    if environment.partition:
        directives.append(f"#SBATCH --partition={environment.partition}")
    if environment.mem_mb_per_cpu:
        directives.append(f"#SBATCH --mem-per-cpu={environment.mem_mb_per_cpu}")
    if environment.account:
        directives.append(f"#SBATCH --account={environment.account}")
    if environment.qos:
        directives.append(f"#SBATCH --qos={environment.qos}")
    if environment.gpus:
        directives.append(f"#SBATCH --gres=gpu:{environment.gpus}")
    if environment.gpu_constraint:
        directives.append(f"#SBATCH --constraint={environment.gpu_constraint}")

    exports = "\n".join(
        f'export {key}="{value}"' for key, value in (environment.environment or {}).items()
    )

    # pc-bach needs its MPI/CHARMM prolog before anything imports pycharmm.
    prolog = ""
    if environment.name == "pcbach":
        prolog = 'if [[ -f "$REPO_ROOT/scripts/pc_bach_env.sh" ]]; then\n  source "$REPO_ROOT/scripts/pc_bach_env.sh"\nfi'

    script = f"""#!/usr/bin/env bash
# GENERATED by workflows/validation_campaign/scripts/submit_slurm.py -- do not edit by hand.
# task: {task.task_id}   goal: {task.goal}   tier: {task.tier}   env: {environment.name}
{chr(10).join(directives)}
set -uo pipefail

REPO_ROOT="${{SLURM_SUBMIT_DIR:-{lib.REPO_ROOT}}}"
cd "$REPO_ROOT"

OUT_DIR="{out_dir}"
mkdir -p "$OUT_DIR"

{prolog}

source "$REPO_ROOT/scripts/resolve_mmml_env.sh"
mmml_resolve_env "$REPO_ROOT"

{exports}

export MMML_CAMPAIGN_RUN_ID="{run_id}"
export MMML_CAMPAIGN_TASK="{task.task_id}"
export MMML_CAMPAIGN_ENV="{environment.name}"
export PYTHONPATH="$REPO_ROOT/workflows/validation_campaign/scripts:${{PYTHONPATH:-}}"

"$MMML_PYTHON" workflows/validation_campaign/scripts/record_status.py \\
  --output-dir "$OUT_DIR" --phase running --environment {environment.name}

set +e
{command.replace("python ", '"$MMML_PYTHON" ', 1)} \\
  > >(tee "$OUT_DIR/stdout.log") 2> >(tee "$OUT_DIR/stderr.log" >&2)
EXIT_CODE=$?
set -e

"$MMML_PYTHON" workflows/validation_campaign/scripts/record_status.py \\
  --output-dir "$OUT_DIR" --phase finished --exit-code "$EXIT_CODE" \\
  --environment {environment.name}

exit "$EXIT_CODE"
"""

    path = out_dir / SCRIPT_NAME
    path.write_text(script)
    path.chmod(0o755)
    return path, script


def submit(campaign: Campaign, task: Task, environment: Environment, run_id: str) -> str:
    path, _ = render_slurm_script(campaign, task, environment, run_id)
    if not shutil.which("sbatch"):
        raise SystemExit(
            f"sbatch not found on this host; cannot submit to {environment.name}. "
            f"Script is ready at {path}"
        )
    proc = subprocess.run(
        ["sbatch", "--parsable", str(path)],
        cwd=lib.REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"sbatch failed for {task.task_id}: {proc.stderr.strip()}")

    job_id = proc.stdout.strip().split(";")[0]
    out_dir = path.parent
    lib.write_status(
        out_dir,
        phase="submitted",
        job_id=job_id,
        environment=environment.name,
        task_id=task.task_id,
        script=str(path),
    )
    return job_id
