"""Render and submit Slurm job scripts (pcbach, scicore, pcstudix).

The rendered script is written into the task's proof directory and is exactly
what runs, so ``prepare`` output can be inspected before ``submit`` dispatches
the identical file.
"""

from __future__ import annotations

import re
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any

import campaign_lib as lib


def _check_qos_runtime(env: dict[str, Any]) -> None:
    """Reject a runtime the qos cannot grant, before Slurm does.

    scicore encodes the wall-clock cap in the qos name (``rtx4090-6hours``).
    Asking for more time than the qos allows is rejected at submission, so catch
    it here where the error can name the offending field.
    """
    qos = str(env.get("qos") or "")
    match = re.search(r"(\d+)\s*hours?", qos)
    if not match:
        return
    cap_min = int(match.group(1)) * 60
    runtime = int(env.get("runtime_min", 0))
    if runtime > cap_min:
        raise SystemExit(
            f"{env['name']}: runtime_min={runtime} exceeds the {cap_min} min cap "
            f"implied by qos {qos!r}. Lower runtime_min in "
            f"workflows/validation_campaign/environments/{env['name']}.yaml, "
            f"or pick a longer qos."
        )


def render(
    cfg: dict[str, Any],
    task_id: str,
    task: dict[str, Any],
    env: dict[str, Any],
    run_id: str,
) -> Path:
    _check_qos_runtime(env)

    out = lib.output_dir(cfg, run_id, task_id, env["name"])
    out.mkdir(parents=True, exist_ok=True)

    # Everything *inside* the script is relative to the cluster's repo root: this
    # file is rendered on one machine and executed on another.
    rel = lib.rel_output_dir(cfg, run_id, task_id, env["name"])
    command = lib.render_command(task, rel, python='"$MMML_PYTHON"')
    lib.write_json(
        out / "request.json", lib.request_payload(task_id, task, env, run_id, command)
    )

    runtime = int(env.get("runtime_min", 120))
    hours, minutes = divmod(runtime, 60)

    directives = [
        f"#SBATCH --job-name=val-{task_id.replace('.', '-')[:90]}",
        f"#SBATCH --partition={env['partition']}",
        f"#SBATCH --nodes={int(env.get('nodes', 1))}",
        f"#SBATCH --ntasks={int(env.get('ntasks', 1))}",
        f"#SBATCH --cpus-per-task={int(env.get('cpus_per_task', 4))}",
        f"#SBATCH --mem-per-cpu={int(env.get('mem_mb_per_cpu', 4000))}M",
        f"#SBATCH --time={hours:02d}:{minutes:02d}:00",
        f"#SBATCH --output={rel / 'slurm-%j.out'}",
        f"#SBATCH --error={rel / 'slurm-%j.err'}",
    ]
    if int(env.get("gpus", 0)) > 0:
        directives.append(f"#SBATCH --gres=gpu:{int(env['gpus'])}")
    for key, flag in (("account", "account"), ("qos", "qos"), ("gpu_constraint", "constraint")):
        if env.get(key):
            directives.append(f"#SBATCH --{flag}={env[key]}")

    # pc-bach must load its MPI/CHARMM prolog before anything imports pycharmm.
    prolog = ""
    if env["name"] == "pcbach":
        prolog = (
            'if [[ -f scripts/pc_bach_env.sh ]]; then\n'
            '  source scripts/pc_bach_env.sh\n'
            'fi'
        )

    quoted_out = shlex.quote(str(rel))
    script = "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# GENERATED by submit_slurm.py for {task_id} @ {env['name']} -- do not edit.",
            *directives,
            "set -uo pipefail",
            "",
            f"cd {lib.repo_root_shell(env)}",
            prolog,
            "",
            "source scripts/resolve_mmml_env.sh",
            'mmml_resolve_env "$PWD"',
            lib.shell_exports(env),
            "",
            f"mkdir -p {quoted_out}",
            '"$MMML_PYTHON" workflows/validation_campaign/scripts/finalize_task.py \\',
            f"  --output-dir {quoted_out} --phase running",
            "",
            "set +e",
            f"{command} \\",
            f"  > {shlex.quote(str(rel / 'stdout.log'))} \\",
            f"  2> {shlex.quote(str(rel / 'stderr.log'))}",
            "task_rc=$?",
            "set -e",
            "",
            '"$MMML_PYTHON" workflows/validation_campaign/scripts/finalize_task.py \\',
            f'  --output-dir {quoted_out} --phase finished --exit-code "$task_rc"',
            "",
            "exit $task_rc",
            "",
        ]
    )

    path = out / "job.slurm"
    path.write_text(script, encoding="utf-8")
    path.chmod(0o755)
    return path


def submit(
    cfg: dict[str, Any],
    task_id: str,
    task: dict[str, Any],
    env: dict[str, Any],
    run_id: str,
) -> str:
    path = render(cfg, task_id, task, env, run_id)
    if not shutil.which("sbatch"):
        raise SystemExit(
            f"sbatch not found on this host, so {env['name']} jobs cannot be submitted "
            f"from here. The script is ready at {path.relative_to(lib.REPO)} -- "
            f"copy it to the cluster, or run submit from a login node."
        )
    proc = subprocess.run(
        ["sbatch", "--parsable", str(path)], cwd=lib.REPO, text=True, capture_output=True
    )
    out = path.parent
    lib.write_json(
        out / "submission.json",
        {
            "returncode": proc.returncode,
            "stdout": proc.stdout.strip(),
            "stderr": proc.stderr.strip(),
            "submitted_utc": lib.utcnow(),
        },
    )
    if proc.returncode != 0:
        raise SystemExit(f"sbatch failed for {task_id}: {proc.stderr.strip()}")

    job_id = proc.stdout.strip().split(";")[0]
    lib.write_json(
        out / "status.json",
        {
            "state": "SUBMITTED",
            "job_id": job_id,
            "environment": env["name"],
            "submitted_utc": lib.utcnow(),
        },
    )
    return job_id
