name: docs_mmml
channels:
  - conda-forge
  - defaults
dependencies:
  # Base deps
  - python=3.12
  - pip>=23
  - setuptools>=61
  - wheel

  # Pip-only installs
  - pip:
      # Project (editable)
      - -e ../

      # Sphinx + theme + extensions (pin for Python 3.10 compatibility)
      - sphinx>=7.2,<8.2
      - pydata-sphinx-theme>=0.16
      - sphinx-design>=0.5
      - sphinx-copybutton>=0.5
