# @package _global_
training:
  # Training parameters
  num_epochs: 100
  learning_rate: 5.0e-4
  batch_size: 1
  
  # No bootstrap
  n_bootstrap: 1
  
  # Loss weights (constant)
  esp_weight_schedule: "constant"
  esp_weight_start: 1000.0
  esp_weight_end: 1000.0
  chg_weight_schedule: "constant"
  chg_weight_start: 1.0
  chg_weight_end: 1.0
  
  # Gradient clipping
  use_grad_clip: true
  grad_clip_norm: 1000.0
  
  # Restart from previous params
  restart_from_checkpoint: null

