name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install build deps
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Install package without deps (avoid heavy optional deps like pycharmm)
        run: pip install --no-deps .
      - name: Lint config sanity
        run: |
          python -V
          python -c "import mmml; print('pkg import ok')" || true
      - name: Install docs deps
        run: pip install -r docs/requirements.txt
      - name: Build docs
        working-directory: docs
        run: |
          sphinx-build -b html . _build/html

